### ISSUE TITLE
authenticator and kubespawner

### ISSUE THREAD

**Issue by tonymills** [hansohn/jupyterhub-ldap-authenticator#2]
Hi, 

I am trying to run jupyterhub with kubespawner against my kubernetes cluster, its working fine with local authentication however when i add the ldap authenticator it will only allow users to login who exist on the jupyterhub server. 

i am passing authentication against ldap but i get a failure pn getpwnam 

i am running the latest docker of jupyterhub and running python 3.6 

it does not work with create homdir True||False

any advice is greatly appreciated

best regards

tony

my config is:
    
   c.JupyterHub.authenticator_class = 'ldapauthenticator.LDAPAuthenticator' 
   c.LDAPAuthenticator.server_hosts = ['ldaps://ldap.dev.svc.cluster.local:636']
   c.LDAPAuthenticator.server_use_ssl = True
   c.LDAPAuthenticator.server_connect_timeout = 10
   c.LDAPAuthenticator.server_receive_timeout = 10
   c.LDAPAuthenticator.server_pool_strategy = 'FIRST'
   c.LDAPAuthenticator.bind_user_dn = 'cn=admin,dc=company,dc=com'
   c.LDAPAuthenticator.bind_user_password = 'admin'
   c.LDAPAuthenticator.user_search_base = 'ou=People,dc=company,dc=com'
   c.LDAPAuthenticator.user_search_filter = '(&(objectClass=posixAccount)(uid={username}))'
   c.LDAPAuthenticator.user_membership_attribute = 'memberOf'
   c.LDAPAuthenticator.group_search_base = 'ou=groups,dc=company,dc=com'
   c.LDAPAuthenticator.group_search_filter = 'memberOf={group}'
   c.LDAPAuthenticator.allowed_groups = ['cn=mygroup,ou=groups,dc=company,dc=com']
   c.LDAPAuthenticator.create_user_home_dir = True

the log shows the following

[D 2018-09-21 12:56:49.415 JupyterHub ldapauthenticator:454] Attempting ldap connection to ['ldaps://ldap.dev.svc.cluster.local:636'] with user 'cn=admin,dc=company,dc=com'
[D 2018-09-21 12:56:49.492 JupyterHub ldapauthenticator:469] Successfully established connection to ['ldaps://ldap.dev.svc.cluster.local:636'] with user 'cn=admin,dc=company,dc=com'
[D 2018-09-21 12:56:49.492 JupyterHub ldapauthenticator:483] Attempting LDAP search using search_filter '(&(objectClass=posixAccount)(uid=tmills))'.
[D 2018-09-21 12:56:49.495 JupyterHub ldapauthenticator:503] LDAP search '(&(objectClass=posixAccount)(uid=tmills))' found 1 result(s).
[D 2018-09-21 12:56:49.495 JupyterHub ldapauthenticator:518] Search results for user 'tmills' returned 'dn' attribute as 'uid=tmills,ou=people,dc=company,dc=com'
[D 2018-09-21 12:56:49.495 JupyterHub ldapauthenticator:530] Search results for user 'tmills' returned 'memberOf' attribute as ['cn=mygroup,ou=groups,dc=company,dc=com']
[D 2018-09-21 12:56:49.495 JupyterHub ldapauthenticator:538] User 'tmills' found in the following allowed ldap groups ['cn=mygroup,ou=groups,dc=company,dc=com']. Proceeding with authentication.
[I 2018-09-21 12:56:49.557 JupyterHub ldapauthenticator:552] User 'tmills' sucessfully authenticated against ldap server ['ldaps://ldap.dev.svc.cluster.local:636'].
[E 2018-09-21 12:56:50.207 JupyterHub web:1670] Uncaught exception POST /hub/login?next= (::ffff:100.100.0.0)
    HTTPServerRequest(protocol='http', host='jupyterhub.dev.company.com', method='POST', uri='/hub/login?next=', version='HTTP/1.1', remote_ip='::ffff:100.100.0.0')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/login.py", line 81, in post
        user = await self.login_user(data)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/handlers/base.py", line 483, in login_user
        await maybe_future(self.authenticator.add_user(user))
      File "/usr/local/lib/python3.6/dist-packages/ldapauthenticator/ldapauthenticator.py", line 263, in add_user
        user_exists = yield gen.maybe_future(self.user_home_dir_exists(username))
      File "/usr/local/lib/python3.6/dist-packages/ldapauthenticator/ldapauthenticator.py", line 275, in user_home_dir_exists
        user = pwd.getpwnam(username)
    KeyError: 'getpwnam(): name not found: tmills'
    
[D 2018-09-21 12:56:50.209 JupyterHub base:880] No template for 500

**Comment by hansohn** [comment]
Hello @tonymills , sorry you're having trouble.

The `pwd.getpwnam(tmills)` call is telling python to search the local passwd database for info about the domain user. Unfortunately I don't have a kubernetes environment to test your exact use case. I can tell you that your jupyterhub server will need to be configured to support domain authentication. I not familiar with Kubespawner enough to know how authenticated sessions are handed off to containers though and there may be additional challenges there. Since Jupyter is pretty much just a webportal to the server's shell, if a domain user can't log in locally they won't be able to login to Jupyterhub.

You can test the pwd.getpwnam call manually by running the following:

```
[root@jupyterhub tmp]# python3
Python 3.6.6 (default, Aug 13 2018, 18:24:23)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pwd
>>> pwd.getpwnam('tmills')
```

Let me know if this helps at all.

**Comment by tonymills** [comment]
Hi Ryan,

Thanks for getting back to me  

I did figure out that I had to configure the server to use the same ldap authentication, however as the jupyterhub does local authentication anyway I’m just a bit confused as to why I would need the ldap authenticator at all. but as i have a working configuration with both jupyterhub and the server allowing access and then kubespawner firing up pods when a user logs in i am very happy and dont want to break it...

Thanks for your help and jupyterhub is great!

Best regards

tony

**Comment by hansohn** [comment]
Glad you we able to resolve everything Tony!

This authenticator eases scoping authentication. Otherwise, by default, any local user account with a shell defined in its profile would be able to log in. This becomes a problem when you have service accounts running on the same server as jupyterhub. You can scope authentication further by using whitelists and blacklists but that would require manual intervention whenever adding/removing users.

This authenticator simplifies this by letting you add/remove users in an LDAP group and letting magic take care of the rest.
