### ISSUE TITLE
LDAP search found 2 result(s). Please narrow search to 1 result.

### ISSUE THREAD

**Issue by HaRo87** [hansohn/jupyterhub-ldap-authenticator#8]
Hi @hansohn,
first off, thanks for putting in effort to get ldap integration into JupyterHub, much appreciated! I managed to configure the ldapauthenticator but I am stuck at the point where the result from the LDAP search comes back. The error message is: 
`LDAP search '(&(objectClass=user)(sAMAccountName=someuser))' found 2 result(s). Please narrow search to 1 result.` 
I am connected to our AD and it seems like every request returns always two results. Do you have any hints how to change the configuration to overcome this issue?

Thanks and cheers from Germany,
Robert

**Comment by hansohn** [comment]
Hello @HaRo87, 
I haven't seen that issue before. To be honest I don't currently have an Active Directory instance at my disposal to test against but I'm assuming that my `c.LDAPAuthenticator.user_search_filter = '(&(objectClass=person)(sAMAccountName={username}))'` filter example is incorrect. 

Can you try modifying the filter to `c.LDAPAuthenticator.user_search_filter = '(&(objectCategory=person)(objectClass=user)(sAMAccountName={username}))'` in your config and retest? 

This should explicitly reduce search scope to user objects only. I was assuming that the `sAMAccountName` attribute was only associated to user objects but maybe that is incorrect. Please let me know the results so that I can update documentation accordingly.

Cheers,
Ryan

**Comment by hansohn** [comment]
Closing issue due to lack of response

**Comment by CS250073** [comment]
Please @hansohn reopen issue as there is a fix in https://github.com/hansohn/jupyterhub-ldap-authenticator/pull/20
